header = { "accept" = "text/html" }

scheme = ["https"]

exclude = [
    "firebaseio.com",
    "example",
    "github.com/beste/firebase-php/(compare|pull|issues)",
    "oauth2.googleapis.com",
    "googleapis.com",
    "gserviceaccount.com",
    ".link",
    '^https://codecov.io',
    '^https://firebase-php\.readthedocs\.io/?$',
    '^https://github.com/pulls',
    '^https://stackoverflow.com', # Since recently returns a 403 for some reason
    '^https://console.firebase.google.com',
    '^https://console.cloud.google.com',
    '^https://jb.gg',
]

exclude_path = [
    "./docs/_build",
    ".vendor"
]

exclude_all_private = false

include_mail = false
